use std::{fs, process::ExitCode};

use anyhow::Result;

use crate::{cli::SetupArgs, project::Project, tools};

pub fn run(project: &Project, args: SetupArgs) -> Result<ExitCode> {
    println!("Recommended tools:");
    println!("  rustfmt       Rust formatter");
    println!("  sccache       compiler cache");
    println!("  mold/lld      faster linker");
    println!("  bacon         background checker");
    println!("  cargo-nextest faster test runner");
    println!();
    print_install_hint();

    if args.write {
        write_cargo_config(project)?;
    }
    if args.install {
        println!();
        println!("Automatic install is planned for a later release.");
        println!("For now, run the commands above and then `plus setup --write`.");
    }

    Ok(ExitCode::SUCCESS)
}

fn print_install_hint() {
    if cfg!(target_os = "linux") {
        println!("Fedora:");
        println!("  sudo dnf install -y rustfmt sccache mold lld");
        println!("Ubuntu/Debian:");
        println!("  sudo apt install -y rustfmt sccache lld");
    } else if cfg!(target_os = "macos") {
        println!("macOS:");
        println!("  brew install sccache mold");
    } else {
        println!("Install rustfmt, sccache, and lld/mold with your system package manager.");
    }
    println!("Cargo tools:");
    println!("  cargo install bacon cargo-nextest");
}

fn write_cargo_config(project: &Project) -> Result<()> {
    if project.cargo_config.exists() {
        println!();
        println!(
            "{} already exists; leaving it untouched.",
            project.cargo_config.display()
        );
        return Ok(());
    }

    let Some(parent) = project.cargo_config.parent() else {
        anyhow::bail!("invalid cargo config path");
    };
    fs::create_dir_all(parent)?;

    let mut body = String::new();
    body.push_str("# Generated by `plus setup --write`.\n");
    body.push_str(
        "# Cargo remains the build engine; this only tunes local developer defaults.\n\n",
    );

    if matches!(tools::sccache_health(), tools::ToolHealth::Ok) {
        body.push_str("[build]\n");
        body.push_str("rustc-wrapper = \"sccache\"\n");
    } else {
        body.push_str("# Install/fix sccache, then uncomment:\n");
        body.push_str("# [build]\n");
        body.push_str("# rustc-wrapper = \"sccache\"\n");
    }

    if let Some(linker) = tools::fast_linker() {
        body.push_str("\n[target.x86_64-unknown-linux-gnu]\n");
        body.push_str(&format!(
            "rustflags = [\"-C\", \"link-arg=-fuse-ld={linker}\"]\n"
        ));
    } else {
        body.push_str("\n# Install mold or lld, then add one of these:\n");
        body.push_str("# [target.x86_64-unknown-linux-gnu]\n");
        body.push_str("# rustflags = [\"-C\", \"link-arg=-fuse-ld=mold\"]\n");
        body.push_str("# rustflags = [\"-C\", \"link-arg=-fuse-ld=lld\"]\n");
    }

    fs::write(&project.cargo_config, body)?;
    println!();
    println!("created {}", project.cargo_config.display());
    Ok(())
}
